export const mierdas = {
  mierdas: [
    {
      nombre: "Mierda",
      footer: "Mierda de caballo",
      descripcion: "Es bonito mira mira mira que pedazo de mierda apestosa",
      img: "mier.jfif",
    },
    {
      nombre: "Mierda",
      footer: "Mierda de caballo",
      descripcion: "Es bonito mira mira mira que pedazo de mierda apestosa",
      img: "mier.jfif",
    },
    {
      nombre: "Mierda",
      footer: "Mierda de caballo",
      descripcion: "Es bonito mira mira mira que pedazo de mierda apestosa",
      img: "mier.jfif",
    },
    {
      nombre: "Mierda",
      footer: "Mierda de caballo",
      descripcion: "Es bonito mira mira mira que pedazo de mierda apestosa",
      img: "mier.jfif",
    },
    {
      nombre: "Mierda",
      footer: "Mierda de caballo",
      descripcion: "Es bonito mira mira mira que pedazo de mierda apestosa",
      img: "mier.jfif",
    },
    {
      nombre: "Mierda",
      footer: "Mierda de caballo",
      descripcion: "Es bonito mira mira mira que pedazo de mierda apestosa",
      img: "mier.jfif",
    },
    {
      nombre: "Mierda",
      footer: "Mierda de caballo",
      descripcion: "Es bonito mira mira mira que pedazo de mierda apestosa",
      img: "mier.jfif",
    },
    {
      nombre: "Mierda",
      footer: "Mierda de caballo",
      descripcion: "Es bonito mira mira mira que pedazo de mierda apestosa",
      img: "mier.jfif",
    },
    {
      nombre: "Mierda",
      footer: "Mierda de caballo",
      descripcion: "Es bonito mira mira mira que pedazo de mierda apestosa",
      img: "mier.jfif",
    },
    {
      nombre: "Mierda",
      footer: "Mierda de caballo",
      descripcion: "Es bonito mira mira mira que pedazo de mierda apestosa",
      img: "mier.jfif",
    },
    {
      nombre: "Mierda",
      footer: "Mierda de caballo",
      descripcion: "Es bonito mira mira mira que pedazo de mierda apestosa",
      img: "mier.jfif",
    },
    {
      nombre: "Mierda",
      footer: "Mierda de caballo",
      descripcion: "Es bonito mira mira mira que pedazo de mierda apestosa",
      img: "mier.jfif",
    },
    {
      nombre: "Mierda",
      footer: "Mierda de caballo",
      descripcion: "Es bonito mira mira mira que pedazo de mierda apestosa",
      img: "mier.jfif",
    },
    {
      nombre: "Mierda",
      footer: "Mierda de caballo",
      descripcion: "Es bonito mira mira mira que pedazo de mierda apestosa",
      img: "mier.jfif",
    },
    {
      nombre: "Mierda",
      footer: "Mierda de caballo",
      descripcion: "Es bonito mira mira mira que pedazo de mierda apestosa",
      img: "mier.jfif",
    },
    {
      nombre: "Mierda",
      footer: "Mierda de caballo",
      descripcion: "Es bonito mira mira mira que pedazo de mierda apestosa",
      img: "mier.jfif",
    },
    {
      nombre: "Mierda",
      footer: "Mierda de caballo",
      descripcion: "Es bonito mira mira mira que pedazo de mierda apestosa",
      img: "mier.jfif",
    },
    {
      nombre: "Mierda",
      footer: "Mierda de caballo",
      descripcion: "Es bonito mira mira mira que pedazo de mierda apestosa",
      img: "mier.jfif",
    },
  ],
};
